# """
# Parameters file. 

# Here you can set the parameter values
# of the run. Above each paramter is a
# comment describing the parameter, 
# it's required type and
# the values that have been tested 
# for it. 

# Most parameters have suggested ranges
# for input to stay within. If thes user
# selects beyond the strict ranges or
# sets to an incorrect type
# the model will not run.

# Note: this file will hopefully be 
# converted to a YML in future 
# iterations of the model.
# """
# The packing density of the model particles
# RANGE: > 0 to <~0.80.
pack_density: 0.78

# Length of the domain in the streamwise direction (mm).
# RANGE: > 0
# TYPE: INT
# TESTED ON: 50-1000 mm
x_max: 100
    
# Grain diameter (mm)
# RANGE: > 0
# TESTED: 0.5, 1.0, 1.5, 2.0
set_diam: 0.5

# The number of bed subregions
# RANGE: > 0
# TYPE: INT
# TESTED: 1, 2, 3, 4, 5-10
num_subregions: 2

# The maximum number of levels permitted in stream
# TESTED: 2, 3, 4, 5,
level_limit: 3

# The number of iterations to run
# RANGE: > 0
# TYPE: INT
# TESTED: 5-10000
n_iterations: 100

# Lamba for poisson dist. used to
# determine the number of entrainment events.
lambda_1: 5

# Distribution used for entrainment hop calculation
# If False: distribution = logNormal
# If True: distribution = Normal
# TYPE: Boolean
normal_dist: False

# Mean/expectation of the logNormal/Normal distribution
mu: 0

# Standard deviation of logNormal/Normal distribution
# RANGE: > 0
# TESTED: 0.25 - 3 [0.25 - 1 for Poissonian flux behavior]
sigma: 1

# Record a snapshot of the stream data (arrays) every 
# n iterations. Set to 1 to record every iteration
snapshot_interval: 1

height_dependancy: True
